### ISSUE TITLE
Quantity of items 

### ISSUE THREAD

**Issue by Krtschboom** [NielsLee/FoodRecords#10]
Hi, I would like to ask if it would be possible to add an quantity field to the items, that if I'm buying more than one of the same item, I wouldn't have to enter the same thing over and over again.
Nice app, thx for sharing it.

**Comment by NielsLee** [comment]
Thanks for sharing your idea! You are right, its a common and important function, will be implemented in the comming version soon!

**Comment by helsingi** [comment]
Hi @NielsLee, you are developing a promising alternative to the complicated grocy.
To add to @Krtschboom suggestion, it would be great if the quantity of items can be pieces, packs, or kgs.
Thanks!

**Comment by NielsLee** [comment]
It seems this feature is highly requested, no problem, I will write it soon ^_^

**Comment by NielsLee** [comment]
https://github.com/NielsLee/FoodRecords/releases/tag/v1.8
