### ISSUE TITLE
Cannot edit saved food tile

### ISSUE THREAD

**Issue by onassis123** [NielsLee/FoodRecords#13]
Hello, I cannot edit food tiles after they are saved. Only the delete option is offered when pressing the 3 dot Menu.

**Comment by helsingi** [comment]
I second this request to add an "Edit" option in addition to the delete option.

**Comment by carlobuccisano** [comment]
I second this as well!

**Comment by NielsLee** [comment]
Ok I'll do that, thanks for the suggestions :)

**Comment by NielsLee** [comment]
[Releases](https://github.com/NielsLee/FoodRecords/releases)
Releases after v1.10 have implemented this feature, Thanks for your suggestion! 🎉
