### ISSUE TITLE
Crash when create duplicate shelf life/food type

### ISSUE THREAD

**Issue by 0w0miki** [NielsLee/FoodRecords#15]
Reproduce step:
1. Go to settings. Add 4 days in shelf life settings.
2. Add 4 days in shelf life settings.

After step 2, the app crashes.

**Comment by NielsLee** [comment]
Thanks for finding this bug, fixed it in the newly publish [v1.3 app](https://github.com/NielsLee/FoodRecords/releases/tag/v1.3)
