### ISSUE TITLE
Feature request: Sort shelf life in the drop-down menu

### ISSUE THREAD

**Issue by 0w0miki** [NielsLee/FoodRecords#16]
For now, there are 8 pre-defined shelf life. I added 4 days in settings for some bread I bought.

When I go to add a new food and choose the shelf life, 4 day(s) is at the end, after 360 day(s). This is a bit strange. And I cannot adjust the order in shelf life settings.

As shelf life is just a list by days, automatic sort should be easy.

**Comment by NielsLee** [comment]
Useful suggestion, have implemented in the newly publish v1.3 app! [v1.3](https://github.com/NielsLee/FoodRecords/releases/tag/v1.3)
