### ISSUE TITLE
过客

### ISSUE THREAD

**Issue by jianhaolan** [NielsLee/FoodRecords#29]
午睡睡不着，突发奇想考虑做个冰箱物品管理app，网上一搜，果然有，所以我来了

**Comment by NielsLee** [comment]
😄 人在哪啊 这个时间睡午觉

**Comment by NielsLee** [comment]
一开始是照着冰箱去做的，结果做着做着就做成现在这样了
果然TODO List是每个做应用的人绕不开的坎🤣
