### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [NielsLee/FoodRecords#9]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7203177694#L1144

diff log: [food3.log](https://github.com/user-attachments/files/16016042/food3.log)

you are sure the APK in https://github.com/NielsLee/FoodRecords/releases/tag/v1.2 was built from https://github.com/NielsLee/FoodRecords/commit/dc03e0ae94fcd81bc6c715bd69e7d4ea21c3d967 ?

maybe clean up the caches and retry? 

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/58d8ee416158662acc06f7f1bf70efa94f97d126

**Comment by NielsLee** [comment]
Rebuild APK and upload again, if still any problem please let me know, thank you!

发件人: Licaon_Kter ***@***.***>
日期: 星期四, 2024年6月27日 23:02
收件人: NielsLee/FoodRecords ***@***.***>
抄送: Subscribed ***@***.***>
主题: [NielsLee/FoodRecords] F-Droid can't build (Issue #9)

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7203177694#L1144

diff log: food3.log<https://github.com/user-attachments/files/16016042/food3.log>

you are sure the APK in https://github.com/NielsLee/FoodRecords/releases/tag/v1.2 was built from dc03e0a<https://github.com/NielsLee/FoodRecords/commit/dc03e0ae94fcd81bc6c715bd69e7d4ea21c3d967> ?

maybe clean up the caches and retry?

―

**Comment by licaon-kter** [comment]
Nope, same diff log :crying_cat_face:

**Comment by NielsLee** [comment]
sry, uploaded again, please helping double check

**Comment by linsui** [comment]
Which jdk do you use?

**Comment by NielsLee** [comment]
Terminal JDK version:
java version "21.0.2" 2024-01-16 LTS
Java(TM) SE Runtime Environment (build 21.0.2+13-LTS-58)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.2+13-LTS-58, mixed mode, sharing)

JDK version in app build.gradle:
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
}

Are these settings related to this issue? I use the same settings in the past two app versions.


发件人: linsui ***@***.***>
日期: 星期六, 2024年6月29日 15:42
收件人: NielsLee/FoodRecords ***@***.***>
抄送: NielsLee ***@***.***>, Comment ***@***.***>
主题: Re: [NielsLee/FoodRecords] F-Droid can't build (Issue #9)

Which jdk do you use?

―

**Comment by linsui** [comment]
Can you rebuild the apk with jdk 17? Currently jdk 21 is only available in debian unstable channel.

**Comment by NielsLee** [comment]
Ok, I have changed my JAVA_HOME to JDK17 and rebuilt (cache cleaned), new app uploaded.
It's a little strange, why didn't I meet this issue in the previous version

发件人: linsui ***@***.***>
日期: 星期六, 2024年6月29日 17:11
收件人: NielsLee/FoodRecords ***@***.***>
抄送: NielsLee ***@***.***>, Comment ***@***.***>
主题: Re: [NielsLee/FoodRecords] F-Droid can't build (Issue #9)

Can you rebuild the apk with jdk 17? Currently jdk 21 is only available in debian unstable channel.

―

**Comment by linsui** [comment]
Hmmm, still the same diff. This is weird. I just tested 1.1 and it's still reproducible. Can you also check if you can still build 1.1 reproducibly?

**Comment by NielsLee** [comment]
[v1.1-app-release.apk.zip](https://github.com/user-attachments/files/16040339/v1.1-app-release.apk.zip)

Ok, this is the release apk built from tag v1.1, thanks for your helping

**Comment by NielsLee** [comment]
I removed JDK21 and rebuild release v1.2, please helping check, if still don’t work, maybe I will take time checking the diff log to find out the true reason, thanks!


发件人: linsui ***@***.***>
日期: 星期六, 2024年6月29日 22:06
收件人: NielsLee/FoodRecords ***@***.***>
抄送: NielsLee ***@***.***>, Comment ***@***.***>
主题: Re: [NielsLee/FoodRecords] F-Droid can't build (Issue #9)

There is similiar diff between your new build of 1.1 and the old apk in release. So there is something changed in your environment.

I'm not sure if changing JAVA_HOME is enough though. Maybe you need to remove jdk 21 completely.

―

**Comment by linsui** [comment]
Still the same diff...

**Comment by NielsLee** [comment]
I just remembered that I changed my Android Tool chain version several days before… sry for I only remembered this now. I will change it back and have another try 😢

发件人: linsui ***@***.***>
日期: 星期六, 2024年6月29日 22:25
收件人: NielsLee/FoodRecords ***@***.***>
抄送: NielsLee ***@***.***>, Comment ***@***.***>
主题: Re: [NielsLee/FoodRecords] F-Droid can't build (Issue #9)

Still the same diff...

**Comment by NielsLee** [comment]
Sorry I can't remember if I made any modifications to my build environment or what changes I might have made (I'm even wondering if updating my macOS version caused the issue, but there's no way to verify this). Are there any other methods to resolve this problem?

**Comment by linsui** [comment]
Generally the jdk is the most likely reason. F-Droid uses openjdk 17. If you didn't change the jdk then maybe something else is changed. But I can't help you debug your macOS... A workaround is building the apk with GitHub Action.

**Comment by NielsLee** [comment]
Thank you, I rebuilt v1.2 by Github Action and uploaded, please helping check if there is still same issue

**Comment by linsui** [comment]
It works, thanks! It would be better if you can reproduce the apk on your local machine though. :)
